
products_dict = {
    'ACOPLADO O CARRETA PLUS': 30,
    'ACOPLADO O CARRETA SUPERIOR 2': 37,
    'ACOPLADO O CARRETA- GS': 17,
    'CAMIONES - SUPERIOR 1': 13,
    'CAMIONES GS': 8,
    'CAMIONES PLUS': 29,
    'CAMIONES SUPERIOR 2': 35,
    'CHILE - REG- GS': 50,
    'FUNCIONARIOS BANCO REGIONAL': 106,
    'GS -REGIONAL 0KM': 91,
    'GS REGIONAL- ALTA GAMA': 51,
    'GS- RC- AUTOMOVILES': 3,
    'GS- REGIONAL - SUDAMERIS': 165,
    'GS-REGIONAL PLUS/MAX': 1,
    'MOTOS ALTA GAMA REG/SUDAMERIS- GS': 52,
    'PERDIDA TOTAL - GS': 5,
    'PERDIDA TOTAL - MOTOCICLETAS': 84,
    'PLAN ACCIONISTAS': 105,
    'REGIONAL - GS': 9,
    'REGIONAL - ITAIPU / CONMEBOL': 85,
    'REGIONAL - MOTOCICLETAS -GS': 20,
    'REGIONAL MAX': 26,
    'REGIONAL SUPERIOR': 34,
    'REGIONAL- FUN.ORSA': 82,
    'REGIONAL- KUROSU / SETAC': 83,
    'RESP. CIVIL AUTOMOVIL - SUPERIOR 2': 33,
    'RESP. CIVIL AUTOMOVILES - PLUS': 27,
    'RESP. CIVIL AUTOMOVILES - SUPERIOR 1': 10,
    'RESP. CIVIL CAMIONES - PLUS': 31,
    'RESP. CIVIL CAMIONES - SUPERIOR 2': 38,
    'RESP. CIVIL CARRETA O ACOP. PLUS': 32,
    'RESP. CIVIL CARRETA O ACOP. SUPERIOR 2': 39,
    'RESP. CIVIL CARRETA O ACOPLADO GS': 24,
    'RESPONSABILIDAD CIVIL & CARTA VERDE': 156,
    'RESPONSABILIDAD CIVIL - MOTOCICLETAS': 21,
    'REGIONAL SUPERIOR': 34
}

via_importacion_dict = {
    'REPRESENTANTE': 1,
    'VIA CHILE': 2,
    'OTROS': 3,
    '': 0
}

via_importacion_list = ['REPRESENTANTE','VIA CHILE','OTROS']