
products_dict = {
    'ACOPLADO O CARRETA PLUS': 30,
    'ACOPLADO O CARRETA SUPERIOR 2': 37,
    'ACOPLADO O CARRETA- GS': 17,
    'CAMIONES - SUPERIOR 1': 13,
    'CAMIONES GS': 8,
    'CAMIONES PLUS': 29,
    'CAMIONES SUPERIOR 2': 35,
    'CHILE - REG- GS': 50,
    'FUNCIONARIOS BANCO REGIONAL': 106,
    'GS -REGIONAL 0KM': 91,
    'GS REGIONAL- ALTA GAMA': 51,
    'GS- RC- AUTOMOVILES': 3,
    'GS- REGIONAL - SUDAMERIS': 165,
    'GS-REGIONAL PLUS/MAX': 1,
    'MOTOS ALTA GAMA REG/SUDAMERIS- GS': 52,
    'PERDIDA TOTAL - GS': 5,
    'PERDIDA TOTAL - MOTOCICLETAS': 84,
    'PLAN ACCIONISTAS': 105,
    'REGIONAL - GS': 9,
    'REGIONAL - ITAIPU / CONMEBOL': 85,
    'REGIONAL - MOTOCICLETAS -GS': 20,
    'REGIONAL MAX': 26,
    'REGIONAL SUPERIOR': 34,
    'REGIONAL- FUN.ORSA': 82,
    'REGIONAL- KUROSU / SETAC': 83,
    'RESP. CIVIL AUTOMOVIL - SUPERIOR 2': 33,
    'RESP. CIVIL AUTOMOVILES - PLUS': 27,
    'RESP. CIVIL AUTOMOVILES - SUPERIOR 1': 10,
    'RESP. CIVIL CAMIONES - PLUS': 31,
    'RESP. CIVIL CAMIONES - SUPERIOR 2': 38,
    'RESP. CIVIL CARRETA O ACOP. PLUS': 32,
    'RESP. CIVIL CARRETA O ACOP. SUPERIOR 2': 39,
    'RESP. CIVIL CARRETA O ACOPLADO GS': 24,
    'RESPONSABILIDAD CIVIL & CARTA VERDE': 156,
    'RESPONSABILIDAD CIVIL - MOTOCICLETAS': 21,
    'REGIONAL SUPERIOR': 34
}

via_importacion_dict = {
    'REPRESENTANTE': 1,
    'VIA CHILE': 2,
    'OTROS': 3,
    '': 0
}

via_importacion_list = ['REPRESENTANTE','VIA CHILE','OTROS']

product_to_capital = {
    'ACOPLADO O CARRETA - SUPERIOR 1': 'Auto Cober. Básica 1',
    'ACOPLADO O CARRETA- GS': 'Auto Cober. Básica 1',
    'ACOPLADO O CARRETA PLUS': 'Auto Cober. Básica 1',
    'ACOPLADO O CARRETA SUPERIOR 2': 'Auto Cober. Básica 1',
    'CAMIONES - SUPERIOR 1': 'Auto Cober. Básica 1',
    'CAMIONES GS': 'Auto Cober. Básica 1',
    'CAMIONES PLUS': 'Auto Cober. Básica 1',
    'CAMIONES SUPERIOR 2': 'Auto Cober. Básica 1',
    'CHILE - REG- GS': 'Auto Cober. Básica 2',
    'FUNCIONARIOS BANCO REGIONAL': 'Auto Cober. Básica 1',
    'GS- RC- AUTOMOVILES': 'Suma Asegurada Art.',
    'GS- REGIONAL - SUDAMERIS': 'Auto Cober. Básica 1',
    'GS -REGIONAL 0KM': 'Auto Cober. Básica 1',
    'GS REGIONAL- ALTA GAMA': 'Auto Cober. Básica 1',
    'GS-REGIONAL PLUS/MAX': 'Auto Cober. Básica 1',
    'MOTOS ALTA GAMA REG/SUDAMERIS- GS': 'Auto Cober. Básica 1',
    'PERDIDA TOTAL - GS': 'Auto Cober. Básica 2',
    'PERDIDA TOTAL - MOTOCICLETAS': 'Auto Cober. Básica 2',
    'PERDIDA TOTAL - PLUS': 'Auto Cober. Básica 2',
    'PLAN ACCIONISTAS': 'Auto Cober. Básica 1',
    'REGIONAL': 'Auto Cober. Básica 1',
    'REGIONAL - GS': 'Auto Cober. Básica 1',
    'REGIONAL - ITAIPU / CONMEBOL': 'Auto Cober. Básica 1',
    'REGIONAL - MOTOCICLETAS -GS': 'Auto Cober. Básica 1',
    'REGIONAL- FUN.ORSA': 'Auto Cober. Básica 1',
    'REGIONAL- KUROSU / SETAC': 'Auto Cober. Básica 1',
    'REGIONAL MAX': 'Auto Cober. Básica 1',
    'REGIONAL SUPERIOR': 'Auto Cober. Básica 1',
    'RESP. CIVIL  CARRETA O ACOP. SUPERIOR 2': 'Suma Asegurada Art.',
    'RESP. CIVIL  CARRETA O ACOPLADO GS': 'Suma Asegurada Art.',
    'RESP. CIVIL AUTOMOVIL - SUPERIOR 2': 'Suma Asegurada Art.',
    'RESP. CIVIL AUTOMOVILES -  PLUS': 'Suma Asegurada Art.',
    'RESP. CIVIL AUTOMOVILES - SUPERIOR 1': 'Suma Asegurada Art.',
    'RESP. CIVIL CAMIONES - PLUS': 'Suma Asegurada Art.',
    'RESP. CIVIL CAMIONES - SUPERIOR 2': 'Suma Asegurada Art.',
    'RESP. CIVIL CAMIONES GS': 'Suma Asegurada Art.',
    'RESP. CIVIL CARRETA O ACOP. PLUS': 'Suma Asegurada Art.',
    'RESPONSABILIDAD CIVIL -  MOTOCICLETAS': 'Suma Asegurada Art.',
    'RESPONSABILIDAD CIVIL & CARTA VERDE': 'Suma Asegurada Art.',
    'RESP. CIVIL CAMIONES - COOPASAM': 'Suma Asegurada Art.',
    'REGIONAL - USD': 'Auto Cober. Básica 1',
    'USD-REGIONAL PLUS/MAX': 'Auto Cober. Básica 1',
    'USD-REGIONAL-SUDAMERIS': 'Auto Cober. Básica 1',
    'USD- RC- AUTOMOVILES': 'Suma Asegurada Art.',
    'CAMIONES USD': 'Auto Cober. Básica 1',
    'ACOPLADO O CARRETA USD': 'Auto Cober. Básica 1',
    'RESP. CIVIL CAMIONES USD': 'Suma Asegurada Art.',
    'REGIONAL - MOTOCICLETAS USD': 'Auto Cober. Básica 1',
    'SUDAMERIS  PROMO 0 KM': 'Auto Cober. Básica 1',
    'USD REGIONAL - ALTA GAMA': 'Auto Cober. Básica 1',
    'MOTOS ALTA GAMA REG/SUDAMERIS-USD': 'Auto Cober. Básica 1',
    'None': 'Suma Asegurada Art.'
}


filter_dict = {
    "Tipo Poliza": "Nombre Tipo Póliza",
    "Contrato/Asegurado": "Nombre Contratante/Asegurado",
    "Ciudad": "Nombre Ciudad",
    "Departamento": "Nombre Departamento",
    "Oficial de Cuenta": "Oficial de Cuenta",
    "Producto": "Nombre Producto",
    "Agente Pincipal": "Nombre Agente Principal",
    "Organizador Principal": "Nombre Organizador Principal",
    "Organizador": "Nombre Organizador",
    "Canal Ventas": "Canal Venta",
    "Año Vehiculo": "Año"
}